"""add_product_images_fields

Revision ID: 4c4cc28ad39a
Revises: 9cd0383ae4bb
Create Date: 2026-05-11 12:16:06.730018

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4c4cc28ad39a'
down_revision: Union[str, Sequence[str], None] = '9cd0383ae4bb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('cover_image', sa.String(length=255), nullable=True))
    op.add_column('products', sa.Column('images', sa.String(length=1000), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'images')
    op.drop_column('products', 'cover_image')
    # ### end Alembic commands ###
