"""Add Order and OrderItem models

Revision ID: 9cd0383ae4bb
Revises: 79dfb8a57e8f
Create Date: 2026-05-08 22:08:20.352889

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9cd0383ae4bb'
down_revision: Union[str, Sequence[str], None] = '79dfb8a57e8f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('order_status_history')
    op.add_column('order_items', sa.Column('name', sa.String(length=255), nullable=False))
    op.add_column('order_items', sa.Column('sku', sa.String(length=100), nullable=True))
    op.add_column('order_items', sa.Column('unit_price', sa.Numeric(precision=12, scale=2), nullable=False))
    op.create_index(op.f('ix_order_items_id'), 'order_items', ['id'], unique=False)
    op.create_index(op.f('ix_order_items_order_id'), 'order_items', ['order_id'], unique=False)
    op.create_index(op.f('ix_order_items_product_id'), 'order_items', ['product_id'], unique=False)
    op.drop_constraint(op.f('order_items_product_id_fkey'), 'order_items', type_='foreignkey')
    op.drop_constraint(op.f('order_items_order_id_fkey'), 'order_items', type_='foreignkey')
    op.create_foreign_key(None, 'order_items', 'products', ['product_id'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key(None, 'order_items', 'orders', ['order_id'], ['id'], ondelete='CASCADE')
    op.drop_column('order_items', 'price_at_order')
    op.add_column('orders', sa.Column('shipping_cost', sa.Numeric(precision=10, scale=2), nullable=False))
    op.add_column('orders', sa.Column('shipping_address', sa.Text(), nullable=True))
    op.add_column('orders', sa.Column('billing_address', sa.Text(), nullable=True))
    op.alter_column('orders', 'total_amount',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               type_=sa.Numeric(precision=12, scale=2),
               existing_nullable=False)
    op.alter_column('orders', 'payment_method',
               existing_type=postgresql.ENUM('card', name='paymentmethod'),
               type_=sa.String(length=50),
               nullable=True)
    op.create_index(op.f('ix_orders_id'), 'orders', ['id'], unique=False)
    op.create_index(op.f('ix_orders_user_id'), 'orders', ['user_id'], unique=False)
    op.drop_constraint(op.f('orders_user_id_fkey'), 'orders', type_='foreignkey')
    op.create_foreign_key(None, 'orders', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.create_foreign_key(op.f('orders_user_id_fkey'), 'orders', 'users', ['user_id'], ['id'])
    op.drop_index(op.f('ix_orders_user_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_id'), table_name='orders')
    op.alter_column('orders', 'payment_method',
               existing_type=sa.String(length=50),
               type_=postgresql.ENUM('card', name='paymentmethod'),
               nullable=False)
    op.alter_column('orders', 'total_amount',
               existing_type=sa.Numeric(precision=12, scale=2),
               type_=sa.NUMERIC(precision=10, scale=2),
               existing_nullable=False)
    op.drop_column('orders', 'billing_address')
    op.drop_column('orders', 'shipping_address')
    op.drop_column('orders', 'shipping_cost')
    op.add_column('order_items', sa.Column('price_at_order', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'order_items', type_='foreignkey')
    op.drop_constraint(None, 'order_items', type_='foreignkey')
    op.create_foreign_key(op.f('order_items_order_id_fkey'), 'order_items', 'orders', ['order_id'], ['id'])
    op.create_foreign_key(op.f('order_items_product_id_fkey'), 'order_items', 'products', ['product_id'], ['id'])
    op.drop_index(op.f('ix_order_items_product_id'), table_name='order_items')
    op.drop_index(op.f('ix_order_items_order_id'), table_name='order_items')
    op.drop_index(op.f('ix_order_items_id'), table_name='order_items')
    op.drop_column('order_items', 'unit_price')
    op.drop_column('order_items', 'sku')
    op.drop_column('order_items', 'name')
    op.create_table('order_status_history',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('order_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('status', postgresql.ENUM('pending', 'paid', 'shipped', 'delivered', 'cancelled', name='orderstatus'), autoincrement=False, nullable=False),
    sa.Column('changed_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], name=op.f('order_status_history_order_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('order_status_history_pkey'))
    )
    # ### end Alembic commands ###
